/**
 * Tapis Systems API
 * The Tapis Systems API provides for management of Tapis Systems including access and transfer methods, permissions and credentials.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { ReqCreateCredential } from '../model/models';
import { RespBasic } from '../model/models';
import { RespCredential } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class CredentialsService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Create or update access credential in the Security Kernel for given system and user
     * Create or update access credential in the Security Kernel for given system and user using a request body.  Requester must be owner of the system.
     * @param systemName 
     * @param userName 
     * @param reqCreateCredential A JSON object specifying a credential.
     * @param pretty 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createUserCredential(systemName: string, userName: string, reqCreateCredential: ReqCreateCredential, pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<RespBasic>;
    public createUserCredential(systemName: string, userName: string, reqCreateCredential: ReqCreateCredential, pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<RespBasic>>;
    public createUserCredential(systemName: string, userName: string, reqCreateCredential: ReqCreateCredential, pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<RespBasic>>;
    public createUserCredential(systemName: string, userName: string, reqCreateCredential: ReqCreateCredential, pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (systemName === null || systemName === undefined) {
            throw new Error('Required parameter systemName was null or undefined when calling createUserCredential.');
        }
        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling createUserCredential.');
        }
        if (reqCreateCredential === null || reqCreateCredential === undefined) {
            throw new Error('Required parameter reqCreateCredential was null or undefined when calling createUserCredential.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        // authentication (TapisJWT) required
        if (this.configuration.apiKeys) {
            const key: string | undefined = this.configuration.apiKeys["TapisJWT"] || this.configuration.apiKeys["X-Tapis-Token"];
            if (key) {
                headers = headers.set('X-Tapis-Token', key);
            }
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<RespBasic>(`${this.configuration.basePath}/v3/systems/credential/${encodeURIComponent(String(systemName))}/user/${encodeURIComponent(String(userName))}`,
            reqCreateCredential,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve credential for given system and user
     * Retrieve credential for given system and user. Requester must be owner of the system. Use query parameter accessMethod&#x3D;&lt;method&gt; to override default access method.
     * @param systemName 
     * @param userName 
     * @param accessMethod 
     * @param pretty 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserCredential(systemName: string, userName: string, accessMethod?: string, pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<RespCredential>;
    public getUserCredential(systemName: string, userName: string, accessMethod?: string, pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<RespCredential>>;
    public getUserCredential(systemName: string, userName: string, accessMethod?: string, pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<RespCredential>>;
    public getUserCredential(systemName: string, userName: string, accessMethod?: string, pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (systemName === null || systemName === undefined) {
            throw new Error('Required parameter systemName was null or undefined when calling getUserCredential.');
        }
        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling getUserCredential.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (accessMethod !== undefined && accessMethod !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>accessMethod, 'accessMethod');
        }
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        // authentication (TapisJWT) required
        if (this.configuration.apiKeys) {
            const key: string | undefined = this.configuration.apiKeys["TapisJWT"] || this.configuration.apiKeys["X-Tapis-Token"];
            if (key) {
                headers = headers.set('X-Tapis-Token', key);
            }
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<RespCredential>(`${this.configuration.basePath}/v3/systems/credential/${encodeURIComponent(String(systemName))}/user/${encodeURIComponent(String(userName))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove credential in the Security Kernel for given system and user
     * Remove credential from the Security Kernel for given system and user. Requester must be owner of the system.
     * @param systemName 
     * @param userName 
     * @param pretty 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeUserCredential(systemName: string, userName: string, pretty?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<RespBasic>;
    public removeUserCredential(systemName: string, userName: string, pretty?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpResponse<RespBasic>>;
    public removeUserCredential(systemName: string, userName: string, pretty?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json'}): Observable<HttpEvent<RespBasic>>;
    public removeUserCredential(systemName: string, userName: string, pretty?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json'}): Observable<any> {
        if (systemName === null || systemName === undefined) {
            throw new Error('Required parameter systemName was null or undefined when calling removeUserCredential.');
        }
        if (userName === null || userName === undefined) {
            throw new Error('Required parameter userName was null or undefined when calling removeUserCredential.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (pretty !== undefined && pretty !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>pretty, 'pretty');
        }

        let headers = this.defaultHeaders;

        // authentication (TapisJWT) required
        if (this.configuration.apiKeys) {
            const key: string | undefined = this.configuration.apiKeys["TapisJWT"] || this.configuration.apiKeys["X-Tapis-Token"];
            if (key) {
                headers = headers.set('X-Tapis-Token', key);
            }
        }

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<RespBasic>(`${this.configuration.basePath}/v3/systems/credential/${encodeURIComponent(String(systemName))}/user/${encodeURIComponent(String(userName))}`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
