/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShareFileRequest { 
    /**
     * The user with which to share
     */
    username: string;
    /**
     * Time in seconds of expiration. minimum=1, maximum=604800 (1 week)
     */
    expiresIn: number;
}

