/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SharedFileObject { 
    /**
     * Username who shared the file/folder
     */
    creator?: string;
    /**
     * Username who was granted access
     */
    sharedWith?: string;
    /**
     * Creation timestamp in UTC
     */
    created?: string;
    /**
     * Number of seconds in which the share was set to expire.
     */
    expiresIn?: number;
    /**
     * Link to the shared file.
     */
    url?: string;
}

